### ISSUE TITLE
ЧЗВ

### ISSUE THREAD

**Issue by zelenkroki** [zelenkroki/bull-cow#4]
1. Къде да чета като за най-глупав потребител на github на български?
2. Качих zip архив на проект, загуби се, как да го открия и как да разархивирам онова, което ми се видя да е начало на хранилище?
3. Как постъпват **_хората_**, когато имат подобни на моите въпроси?

**Comment by krasimirstoev** [comment]
може да се затвори това issue, файловете са налични в upload/

**Comment by zelenkroki** [comment]
Както съм го записала 3 въпроса в един, ще го отбележа като решена задача, а ще трябва да отворя нови.
Благодаря за помощта, @krasimirstoev.
